markdown: kramdown
theme: jekyll-theme-slate
title: Matt Bell
description: 
analytics: true
show_downloads: false
social:
  twitter: mbell88
  instagram: mbelly88
  linkedin: matt-bell-18126341
  github: bellmatt
  medium: mattbell.dev
