markdown: kramdown
theme: jekyll-theme-slate
title: Matt Bell
description: 
google_analytics: G-Z0PZZDZ6JZ
show_downloads: false
social:
  twitter: mbell88
  instagram: mbelly88
  linkedin: matt-bell-18126341
  github: bellmatt