baseURL = "https://bellmatt.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Matt Bell"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
